name: Build Nightly Container

on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true

jobs:

  build-nightly:
    runs-on: ubuntu-latest
    name: Build Backend
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v2
        with:
          image: tonistiigi/binfmt:latest
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Nightly Image
        run: |
          docker build --push --no-cache \
            --tag ${{ vars.DOCKERHUB_REPONAME }}/${{ vars.DOCKERHUB_IMAGENAME}}:${{ inputs.tag }}  \
            --build-arg COMMIT=$(git rev-parse HEAD) \
            --platform linux/amd64 --file=./Dockerfile .
